services:
  - type: web
    name: qbooker-marketing
    runtime: static
    rootDir: marketing
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        sync: false
      - key: VITE_ADMIN_APP_URL
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    name: qbooker-customer-admin
    runtime: static
    rootDir: customer-admin
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        sync: false
      - key: VITE_MARKETING_URL
        sync: false
      - key: VITE_STAFF_APP_URL
        sync: false
      - key: VITE_CUSTOMER_APP_URL
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    name: qbooker-staff
    runtime: static
    rootDir: staff
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    name: qbooker-customer
    runtime: static
    rootDir: customer
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    name: qbooker-system-admin
    runtime: static
    rootDir: admin
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL